services:

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: weather-report
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  producer:
    build:
      context: ./weather-producer
      dockerfile: Dockerfile
    environment:
      SPRING_RABBITMQ_USERNAME: root
      SPRING_RABBITMQ_PASSWORD: 12345
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/distributed-system
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 12345
    depends_on:
      - db
    ports:
      - "8082:8082"

volumes:
  postgres_data: